# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: devel
          extra-packages: any::rcmdcheck, any::XML, any::tinytex, any::magick
          needs: check

      - name: Install latex
        uses: r-lib/actions/setup-tinytex@v2 
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX
#          
#      - name: Install additional LaTeX packages (non-Windows)
#        if: inputs.runner_os != 'Windows'
#        run: |
#          tlmgr install bera nowidow parnotes marginfix etoolbox titlesec sectsty framed enumitem parskip soul placeins footmisc changepage xstring caption mathtools pdfcrop
#          tlmgr list --only-installed
      
      - uses: r-lib/actions/check-r-package@v2

      - name: BiocCheck
        run: |
          BiocManager::install("BiocCheck")
          BiocCheck::BiocCheck(".")
        shell: Rscript {0}
